# Generated by Django 4.0.4 on 2022-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('workoutLength', models.IntegerField(default=0)),
                ('workout1', models.CharField(max_length=1000)),
                ('workout2', models.CharField(max_length=1000)),
                ('workout3', models.CharField(max_length=1000)),
                ('workout4', models.CharField(max_length=1000)),
                ('workout5', models.CharField(max_length=1000)),
                ('workout6', models.CharField(max_length=1000)),
                ('workout7', models.CharField(max_length=1000)),
                ('workout8', models.CharField(max_length=1000)),
                ('workout9', models.CharField(max_length=1000)),
                ('workout10', models.CharField(max_length=1000)),
                ('workout11', models.CharField(max_length=1000)),
                ('workout12', models.CharField(max_length=1000)),
            ],
        ),
    ]
